version: "3.3"
services:
  dms-faker:
    image: bosagora/dms-faker:v0.x.x-c819e3
    container_name: dms-faker
    restart: always
    environment:
      PRODUCTION_NET_URL: http://agora-el-node:8545
      PRODUCTION_CHAIN_ID: 24680
      TOKEN_CONTRACT_ADDRESS: "0xFDa3d1ff3C570c2f76c2157Ef7A8640A75794eD9"
      LEDGER_CONTRACT_ADDRESS: "0x0B92368a93549FD57e42bb29849438F72DAEf1F6"
      PHONE_LINKER_CONTRACT_ADDRESS: "0xaE7018CaF086EB2Ca62eAA7b91B61dDA6b046F70"
      LOYALTY_PROVIDER_CONTRACT_ADDRESS: "0xf9F610108d001Bd1A672f63E9B9b78d723ac6Ced"
      SHOP_CONTRACT_ADDRESS: "0xDb62De0aD297cfDa76EE80Cc909177aAF5C7f322"
    networks:
      - bosagora_network

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
