version: "3.3"
services:
  dms-osx-faker:
    image: bosagora/dms-osx-faker:latest
    container_name: dms-osx-faker
    restart: always
    environment:
      RPC_URL: http://agora-el-node:8545
    networks:
      - bosagora_network

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
