version: "3.3"
services:
  dms-osx-faker:
    image: bosagora/dms-osx-faker:v0.x.x-ee25bc
    container_name: dms-osx-faker
    restart: always
    environment:
      PRODUCTION_NET_URL: http://agora-el-node:8545
      PRODUCTION_CHAIN_ID: 24680
      TOKEN_CONTRACT_ADDRESS: "0xFDa3d1ff3C570c2f76c2157Ef7A8640A75794eD9"
      LEDGER_CONTRACT_ADDRESS: "0x12c316e0358d914A211A3d477db912A503cFCc21"
      PHONE_LINKER_CONTRACT_ADDRESS: "0xaE7018CaF086EB2Ca62eAA7b91B61dDA6b046F70"
    networks:
      - bosagora_network

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
