version: "3.3"
services:
  dms-osx-faker:
    image: bosagora/dms-osx-faker:v0.x.x-e32808
    container_name: dms-osx-faker
    restart: always
    environment:
      RPC_URL: http://agora-el-node:8545
      TOKEN_CONTRACT_ADDRESS: "0xFDa3d1ff3C570c2f76c2157Ef7A8640A75794eD9"
      LEDGER_CONTRACT_ADDRESS: "0x52bB9258733086243Ad1a4A818945F94BCAd05B9"
      EMAIL_LINKER_CONTRACT_ADDRESS: "0xf1CEFe1b28ee6768597f177eca6616aD44C96418"
    networks:
      - bosagora_network

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
