#!/bin/bash

if ! docker network ls | grep -q 'bosagora_network'
then
  docker network create --subnet=172.200.0.0/16 bosagora_network
  sleep 2
fi

if docker-compose ls | grep -q 'graph'
then
  ./agora/cmd.sh stop-graph
fi

if docker-compose ls | grep -q 'ipfs-private'
then
  ./agora/cmd.sh stop-ipfs
fi

if docker-compose ls | grep -q 'faker'
then
  ./agora/cmd.sh stop-faker
  sleep 2
fi

if docker-compose ls | grep -q 'boa-scan'
then
  ./agora/cmd.sh stop-boa-scan
  sleep 2
fi

if docker-compose ls | grep -q 'postgres'
then
  ./agora/cmd.sh stop-db
  sleep 2
fi

if docker-compose ls | grep -q 'relay'
then
  ./agora/cmd.sh stop-relay
  sleep 2
fi

if docker-compose ls | grep -q 'nodes'
then
  ./agora/cmd.sh stop
  sleep 2
fi

./agora/cmd.sh clear

./agora/cmd.sh start

sleep 5
#
#./agora/cmd.sh start-db
#
#sleep 5
#
#./agora/cmd.sh init-db
#
#sleep 5
#
#./agora/cmd.sh start-boa-scan
#
#sleep 5


CURRENT_POS="$(pwd)"
cd submodules/del-osx
yarn install --pure-lockfile
cd packages/contracts
cp -f env/.env.sample env/.env
rm -rf .openzeppelin
yarn deploy:devnet

cd "$CURRENT_POS"

cd submodules/dms-osx
yarn install --pure-lockfile
cd packages/contracts
cp -f env/.env.sample env/.env
rm -rf .openzeppelin
yarn deploy:devnet

cd "$CURRENT_POS"

sleep 5

./stop

cd agora
rm chain.zip
zip -r chain.zip chain/*

cd "$CURRENT_POS"
