#!/bin/bash

if docker-compose ls | grep -q 'graph'
then
  ./agora/cmd.sh stop-graph
fi

if docker-compose ls | grep -q 'ipfs-private'
then
  ./agora/cmd.sh stop-ipfs
fi

if docker-compose ls | grep -q 'faker'
then
  ./agora/cmd.sh stop-faker
fi

if docker-compose ls | grep -q 'boa-scan'
then
  ./agora/cmd.sh stop-boa-scan
fi

if docker-compose ls | grep -q 'postgres'
then
  ./agora/cmd.sh stop-db
fi

if docker-compose ls | grep -q 'nodes'
then
  ./agora/cmd.sh stop
fi

if docker network ls | grep -q 'bosagora_network'
then
  ./agora/cmd.sh remove-network
fi
