version: '3.3'
services:
  redis_db:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    container_name: redis_db
    command: redis-server
    volumes:
      - redis_db:/data
    networks:
      - bosagora_network

  boascan:
    depends_on:
      - redis_db
    image: bosagora/boa-scan:agora-arm64
    restart: always
    stop_grace_period: 5m
    container_name: 'boascan'
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      - ../config/boascan/common-boascan.env
    environment:
      MICROSERVICE_SC_VERIFIER_ENABLED: 'false'
      MICROSERVICE_VISUALIZE_SOL2UML_ENABLED: 'false'
      MICROSERVICE_SIG_PROVIDER_ENABLED: 'false'
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
    ports:
      - "14000:14000"
    volumes:
      - ./logs/:/app/logs/
    networks:
      - bosagora_network

volumes:
  redis_db:

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
