version: '3.3'
services:
  del-validator0:
    image: bosagora/del-validator:v0.x.x-faac19
    container_name: del-validator0
    restart: always
    ports:
      - '7080:7080'
    environment:
      PRODUCTION_NET_URL: http://agora-el-node:8545
      PRODUCTION_CHAIN_ID: 24680
      NODE_HOST: 0.0.0.0
      NODE_PORT: 7080
      NODE_EXTERNAL_IP: del-validator0
      NODE_DELAY_LOADING: 1000
      LOGGING_LEVEL: verbose
      LINK_COLLECTION_ADDRESS: 0xf1CEFe1b28ee6768597f177eca6616aD44C96418
      VALIDATOR_KEY: 0xd56ca4bc48b3114d7738236c748e2b75c32c9b1e8b2beb118b83e527ea6ef619
      AUTHENTICATION_MODE: 0
    networks:
      - bosagora_network

  del-validator1:
    image: bosagora/del-validator:v0.x.x-faac19
    container_name: del-validator1
    restart: always
    ports:
      - '7081:7080'
    environment:
      PRODUCTION_NET_URL: http://agora-el-node:8545
      PRODUCTION_CHAIN_ID: 24680
      NODE_HOST: 0.0.0.0
      NODE_PORT: 7080
      NODE_EXTERNAL_IP: del-validator1
      NODE_DELAY_LOADING: 1000
      LOGGING_LEVEL: verbose
      LINK_COLLECTION_ADDRESS: 0xf1CEFe1b28ee6768597f177eca6616aD44C96418
      VALIDATOR_KEY: 0x4f5e0132a89da55b6fcf9a61e3799af0f855c7386fb728ecf208124a02379a25
      AUTHENTICATION_MODE: 0
    networks:
      - bosagora_network
    depends_on:
      - del-validator0

  del-validator2:
    image: bosagora/del-validator:v0.x.x-faac19
    container_name: del-validator2
    restart: always
    ports:
      - '7082:7080'
    environment:
      PRODUCTION_NET_URL: http://agora-el-node:8545
      PRODUCTION_CHAIN_ID: 24680
      NODE_HOST: 0.0.0.0
      NODE_PORT: 7080
      NODE_EXTERNAL_IP: del-validator2
      NODE_DELAY_LOADING: 1000
      LOGGING_LEVEL: verbose
      LINK_COLLECTION_ADDRESS: 0xf1CEFe1b28ee6768597f177eca6616aD44C96418
      VALIDATOR_KEY: 0xc6bb4869d5c9368c7b8c5da7e3cd01e0e9a4a9984e1e2a1f3d4190e08830059f
      AUTHENTICATION_MODE: 0
    networks:
      - bosagora_network
    depends_on:
      - del-validator1

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
