version: '3.3'
services:
  del-validator0:
    image: bosagora/del-validator:v0.x.x-db8657
    container_name: del-validator0
    restart: always
    ports:
      - '7080:7080'
    environment:
      PRODUCTION_NET_URL: http://agora-el-node:8545
      PRODUCTION_CHAIN_ID: 24680
      NODE_HOST: 0.0.0.0
      NODE_PORT: 7080
      NODE_EXTERNAL_IP: del-validator0
      NODE_DELAY_LOADING: 1000
      LOGGING_LEVEL: verbose
      LINK_COLLECTION_ADDRESS: 0xf1CEFe1b28ee6768597f177eca6616aD44C96418
      VALIDATOR_KEY: ${VALIDATOR_KEY0}
      AUTHENTICATION_MODE: 2
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_ACCOUNT: ${SMTP_ACCOUNT0}
      SMTP_PASSWORD: ${SMTP_PASSWORD0}
    networks:
      - bosagora_network

  del-validator1:
    image: bosagora/del-validator:v0.x.x-db8657
    container_name: del-validator1
    restart: always
    ports:
      - '7081:7080'
    environment:
      PRODUCTION_NET_URL: http://agora-el-node:8545
      PRODUCTION_CHAIN_ID: 24680
      NODE_HOST: 0.0.0.0
      NODE_PORT: 7080
      NODE_EXTERNAL_IP: del-validator1
      NODE_DELAY_LOADING: 1000
      LOGGING_LEVEL: verbose
      LINK_COLLECTION_ADDRESS: 0xf1CEFe1b28ee6768597f177eca6616aD44C96418
      VALIDATOR_KEY: ${VALIDATOR_KEY1}
      AUTHENTICATION_MODE: 2
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_ACCOUNT: ${SMTP_ACCOUNT1}
      SMTP_PASSWORD: ${SMTP_PASSWORD1}
    networks:
      - bosagora_network
    depends_on:
      - del-validator0

  del-validator2:
    image: bosagora/del-validator:v0.x.x-6fc5b3
    container_name: del-validator2
    restart: always
    ports:
      - '7082:7080'
    environment:
      PRODUCTION_NET_URL: http://agora-el-node:8545
      PRODUCTION_CHAIN_ID: 24680
      NODE_HOST: 0.0.0.0
      NODE_PORT: 7080
      NODE_EXTERNAL_IP: del-validator2
      NODE_DELAY_LOADING: 1000
      LOGGING_LEVEL: verbose
      LINK_COLLECTION_ADDRESS: 0xf1CEFe1b28ee6768597f177eca6616aD44C96418
      VALIDATOR_KEY: ${VALIDATOR_KEY2}
      AUTHENTICATION_MODE: 2
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_ACCOUNT: ${SMTP_ACCOUNT2}
      SMTP_PASSWORD: ${SMTP_PASSWORD2}
    networks:
      - bosagora_network
    depends_on:
      - del-validator1

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
