version: "3.3"
services:
  dms-node:
    image: bosagora/dms-node:v0.x.x-ef743b
    container_name: dms-node
    restart: always
    ports:
      - '7600:7600'
    volumes:
      - ./config:/app/config
    environment:
      HOST_IP: 0.0.0.0
      HOST_PORT: 7600
      PRODUCTION_NET_URL: http://agora-el-node:8545
      PRODUCTION_CHAIN_ID: 24680
      DATABASE_HOST: "postgres"
      DATABASE_USER: "agora"
      DATABASE_NAME: "postgres"
      DATABASE_SCHEME:
      DATABASE_PASSWORD: "12345678"
      DATABASE_PORT: "5432"
      TOKEN_CONTRACT_ADDRESS: ${TOKEN_CONTRACT_ADDRESS}
      LEDGER_CONTRACT_ADDRESS: ${LEDGER_CONTRACT_ADDRESS}
      PHONE_LINKER_CONTRACT_ADDRESS: ${PHONE_LINKER_CONTRACT_ADDRESS}
      SHOP_CONTRACT_ADDRESS: ${SHOP_CONTRACT_ADDRESS}
      CURRENCY_RATE_CONTRACT_ADDRESS: ${CURRENCY_RATE_CONTRACT_ADDRESS}
      LOYALTY_PROVIDER_CONTRACT_ADDRESS: ${LOYALTY_PROVIDER_CONTRACT_ADDRESS}
      LOYALTY_CONSUMER_CONTRACT_ADDRESS: ${LOYALTY_CONSUMER_CONTRACT_ADDRESS}
      LOYALTY_EXCHANGER_CONTRACT_ADDRESS: ${LOYALTY_EXCHANGER_CONTRACT_ADDRESS}
      STORE_PURCHASE_CONTRACT_ADDRESS: ${STORE_PURCHASE_CONTRACT_ADDRESS}
      NODE_IPFS_GATEWAY_URL: http://ipfs0:8080
      WAITED_PROVIDE: 60
      VALIDATOR01: ${VALIDATOR01}
      VALIDATOR02: ${VALIDATOR02}
      VALIDATOR03: ${VALIDATOR03}
      VALIDATOR04: ${VALIDATOR04}
      VALIDATOR05: ${VALIDATOR05}
      VALIDATOR06: ${VALIDATOR06}
      VALIDATOR07: ${VALIDATOR07}
      VALIDATOR08: ${VALIDATOR08}
      VALIDATOR09: ${VALIDATOR09}
      VALIDATOR10: ${VALIDATOR10}
      VALIDATOR11: ${VALIDATOR11}
      VALIDATOR12: ${VALIDATOR12}
      VALIDATOR13: ${VALIDATOR13}
      VALIDATOR14: ${VALIDATOR14}
      VALIDATOR15: ${VALIDATOR15}
      VALIDATOR16: ${VALIDATOR16}
    networks:
      - bosagora_network

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
