version: '3.7'

services:
  ipfs:
    platform: linux/amd64
    container_name: ipfs
    hostname: ipfs
    image: ipfs/go-ipfs
    ports:
      - '4001:4001'
      - '4001:4001/udp'
      - '5001:5001'
      - '8080:8080'
    volumes:
      - volume_ipfs:/data/ipfs
      - volume_staging:/staging
    restart: always
    networks:
      - bosagora_network

volumes:
  volume_ipfs:
  volume_staging:

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
