version: '3.3'
services:
  postgres:
    image: postgres:12.0
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: agora
      POSTGRES_DB: graph
      PGDATA: /postgresql/data
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgres_db:/postgresql/data
    networks:
      - bosagora_network

volumes:
  postgres_db:

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
