version: "3.3"
services:
  dms-osx-relay:
    image: bosagora/dms-osx-relay:v0.x.x-b36749
    container_name: dms-osx-relay
    restart: always
    ports:
      - '7070:7070'
    environment:
      HOST_IP: 0.0.0.0
      HOST_PORT: 7070
      PRODUCTION_NET_URL: http://agora-el-node:8545
      PRODUCTION_CHAIN_ID: 24680
      TOKEN_CONTRACT_ADDRESS: "0xFDa3d1ff3C570c2f76c2157Ef7A8640A75794eD9"
      LEDGER_CONTRACT_ADDRESS: "0x52bB9258733086243Ad1a4A818945F94BCAd05B9"
      EMAIL_LINKER_CONTRACT_ADDRESS: "0xf1CEFe1b28ee6768597f177eca6616aD44C96418"
      MANAGER_KEY: "0xf17b5048d0acdcabcc1fa5f3e1aa6753243d4309a6a30f951d5712cb50c86671"
    networks:
      - bosagora_network

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
