version: "3.3"
services:
  dms-osx-relay-db:
    image: postgres:12.0
    container_name: dms-osx-relay-db
    ports:
      - '5430:5432'
    restart: always
    command:
      [
        "postgres",
        "-c", "shared_preload_libraries=pg_stat_statements",
        "-c", "max_connections=1000"
      ]
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: agora
      POSTGRES_DB: postgres
      PGDATA: /postgresql/data
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - relay_db_volume:/postgresql/data
    networks:
      - bosagora_network

  dms-osx-relay:
    image: bosagora/dms-osx-relay:v0.x.x-337934
    container_name: dms-osx-relay
    restart: always
    ports:
      - '7070:7070'
    volumes:
      - ./config:/app/config
    environment:
      HOST_IP: 0.0.0.0
      HOST_PORT: 7070
      PRODUCTION_NET_URL: http://agora-el-node:8545
      PRODUCTION_CHAIN_ID: 24680
      DATABASE_HOST: "dms-osx-relay-db"
      DATABASE_USER: "agora"
      DATABASE_NAME: "postgres"
      DATABASE_PASSWORD: "12345678"
      DATABASE_PORT: "5432"
      TOKEN_CONTRACT_ADDRESS: ${TOKEN_CONTRACT_ADDRESS}
      LEDGER_CONTRACT_ADDRESS: ${LEDGER_CONTRACT_ADDRESS}
      PHONE_LINKER_CONTRACT_ADDRESS: ${PHONE_LINKER_CONTRACT_ADDRESS}
      SHOP_CONTRACT_ADDRESS: ${SHOP_CONTRACT_ADDRESS}
      CURRENCY_RATE_CONTRACT_ADDRESS: ${CURRENCY_RATE_CONTRACT_ADDRESS}
      CERTIFIER: ${CERTIFIER}
      CERTIFIER01: ${CERTIFIER01}
      CERTIFIER02: ${CERTIFIER02}
      CERTIFIER03: ${CERTIFIER03}
      CERTIFIER04: ${CERTIFIER04}
      CERTIFIER05: ${CERTIFIER05}
      CERTIFIER06: ${CERTIFIER06}
      CERTIFIER07: ${CERTIFIER07}
      CERTIFIER08: ${CERTIFIER08}
      CERTIFIER09: ${CERTIFIER09}
      CERTIFIER10: ${CERTIFIER10}
      ACCESS_KEY: ${ACCESS_KEY}
      CALLBACK_ACCESS_KEY: ${CALLBACK_ACCESS_KEY}
      CALLBACK_ENDPOINT: ${CALLBACK_ENDPOINT}
      EXPO_ACCESS_TOKEN: ${EXPO_ACCESS_TOKEN}
    networks:
      - bosagora_network

volumes:
  relay_db_volume:

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
